"""Repository functions for creator portal tokens (migration 009).

Pure SQL following the app/repositories/*.py convention. Token strings are
generated by the router (secrets.token_urlsafe); this module only persists
and resolves them.
"""

from typing import Any

from app.core.db import connection, fetch_all, fetch_one


def issue_token(creator_id: str, token: str) -> dict[str, Any]:
    """Revoke any active tokens for the creator, then persist the new one.

    One active token per creator keeps revocation trivial: rotating always
    invalidates every previously shared link.
    """

    revoke_query = """
        UPDATE creator_portal_token
        SET status = 'revoked', revoked_at = now()
        WHERE creator_id = %(creator_id)s AND status = 'active'
    """
    insert_query = """
        INSERT INTO creator_portal_token (creator_id, token)
        VALUES (%(creator_id)s, %(token)s)
        RETURNING *
    """
    with connection() as conn:
        with conn.cursor() as cur:
            cur.execute(revoke_query, {"creator_id": creator_id})
            cur.execute(insert_query, {"creator_id": creator_id, "token": token})
            row = cur.fetchone()
        conn.commit()
    if row is None:
        raise RuntimeError("creator_portal_token insert did not return a row.")
    return dict(row)


def get_active_by_token(token: str) -> dict[str, Any] | None:
    query = """
        SELECT * FROM creator_portal_token
        WHERE token = %(token)s AND status = 'active'
        LIMIT 1
    """
    return fetch_one(query, {"token": token})


def touch_last_seen(token_id: str) -> None:
    query = """
        UPDATE creator_portal_token
        SET last_seen_at = now()
        WHERE id = %(token_id)s
    """
    with connection() as conn:
        with conn.cursor() as cur:
            cur.execute(query, {"token_id": token_id})
        conn.commit()


def revoke_for_creator(creator_id: str) -> int:
    query = """
        UPDATE creator_portal_token
        SET status = 'revoked', revoked_at = now()
        WHERE creator_id = %(creator_id)s AND status = 'active'
        RETURNING id
    """
    rows = fetch_all(query, {"creator_id": creator_id})
    return len(rows)


def list_for_creator(creator_id: str) -> list[dict[str, Any]]:
    query = """
        SELECT id, creator_id, status, created_at, revoked_at, last_seen_at
        FROM creator_portal_token
        WHERE creator_id = %(creator_id)s
        ORDER BY created_at DESC
    """
    return fetch_all(query, {"creator_id": creator_id})
